[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
brix = "6xonaQdmV1b7QqfaiGvEnrbo6xH318odiXvLQ8Ebsy94"

[programs.devnet]
brix = "6xonaQdmV1b7QqfaiGvEnrbo6xH318odiXvLQ8Ebsy94"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
